#!/bin/bash


if [ "$__SYSTEM_DESKTOP_ENVIRONMENT" == "gnome" ]; then


	$__SYSTEM_SUDO_INSTALL numix-icon-theme-circle
	
	
	if [ "$__SYSTEM_DISTRO_FAMILY" == "debian" ]; then
	
	
		$__SYSTEM_SUDO_INSTALL arc-theme
	
	
	fi
	
	
fi


if [ "$__SYSTEM_DISTRO" == "debian" ]; then
	
	
	if [ ! -d /usr/share/fonts/truetype/___fonts ]; then
	
		sudo mkdir -p /usr/share/fonts/truetype/___fonts
		
		sudo cp -Rf /dropbox/configuration/font/___fonts/* /usr/share/fonts/truetype/___fonts/
		
		fc-cache -v
		
	fi
	

fi


$__SYSTEM_SUDO_INSTALL guake


sudo ln -s $HOME/.config/ca2/localconfig/dedicatory.txt $HOME/Desktop/dedicatory.txt



gio set -t string $HOME/Desktop/dedicatory.txt metadata::custom-icon file:///dropbox/ca2/dedicatory/tree.png

