// This file is automatically generated and overwritten by netnode

#pragma once

#include "../library/include.h"
#include "../library/interface.h"
#include "../library/music.h"
#include "../library/source.h"
#include "../library/veriwell.h"
#include "../library/votagus.h"

